card_price:
  target: all
  outputs:
    all:
      type: sqlserver
      driver: 'ODBC Driver 18 for SQL Server'
      server: 'poketcgdata.database.windows.net'
      port: 1433
      database: poketcgdata_dev
      schema: cards
      user: 'service_admin@poketcgdata'
      password: 'Ericken2024'
      trust_cert: True